on:
  push:
    branches: 
      - "main"

name: onPush

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: 'Create env file'
        run: |
          touch .env
          echo MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }} >> .env
          echo ARBITRUM_RPC_URL=${{ secrets.ARBITRUM_RPC_URL }} >> .env
          
      - name: Run unit tests
        run: forge test

      - name: Run slither mainnet Compounders
        uses: crytic/slither-action@v0.2.0
        with:
          solc-version: 0.8.17
          fail-on: medium
          target: src/mainnet/compounders
      
      # - name: Run slither mainnet Concentrators
      #   uses: crytic/slither-action@v0.2.0
      #   with:
      #     solc-version: 0.8.17
      #     fail-on: medium
      #     target: src/mainnet/concentrators

      - name: Run slither Arbitrum Compounders
        uses: crytic/slither-action@v0.2.0
        with:
          solc-version: 0.8.17
          fail-on: medium
          target: src/arbitrum/compounders/gmx

      - name: Run slither Shared
        uses: crytic/slither-action@v0.2.0
        with:
          solc-version: 0.8.17
          fail-on: medium
          target: src/shared/compounders